### ISSUE TITLE
Dataset zipfile broken

### ISSUE THREAD

**Issue by anwai98** [SYCAI-Technologies/curvas-challenge#1]
Hi team,

Thanks for organizing the challenge and releasing the dataset.

Looks like the dataset cannot be unzipped with the latest release link at https://zenodo.org/records/12687192, and returns `zipfile corrupt` error while trying to unzip the file.

To reproduce:
```bash
$ wget https://zenodo.org/records/12687192/files/training_set.zip
$ unzip training_set.zip
```

The error I get at the final step:
```bash
$ unzip training_set.zip 
Archive:  training_set.zip
warning [training_set.zip]:  1981410477 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [training_set.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

Would appreciate your help on this and if the files could be zipped and reuploaded again to zenodo.

PS: A hot-fix works at the moment to try to fix the zipfile using:
```bash
zip -FF training_set.zip --out training_set_fixed.zip
unzip training_set_fixed.zip
```

**Comment by anwai98** [comment]
Hi @mrm-sycai,

Is this fixed now?

**Comment by mrm-sycai** [comment]
Hi @anwai98 ,

Idk which version gave you problems (maybe the first one?). In the last version of the CURVAS dataset should be fixed.

Regards,

**Comment by anwai98** [comment]
Hi @mrm-sycai,

Thanks for your quick response. I will check it out later today then! (I tried the hack-fix a while ago when I opened the issue and was happy with my hack-fix).

**Comment by anwai98** [comment]
Hi @mrm-sycai,

The error still exists: downloaded the zipfile using `wget https://zenodo.org/records/12687192/files/training_set.zip` and then tried `unzip training_set.zip`.

**Comment by mrm-sycai** [comment]
Hi @anwai98,

Try it with the newer version please, this should be fixed with the last one. It also includes all images of the last edition of the challenge.

Here: https://zenodo.org/records/13767408
